workflows:
  ios-testflight:
    name: iOS TestFlight (Expo prebuild + Xcode)
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: "Codemagic"

    environment:
      vars:
        BUNDLE_ID: com.rietamura.bluelang
        APP_PATH: mobile
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.rietamura.bluelang

    scripts:
      - name: Print versions and install JS deps (mobile/)
        script: |
          node -v
          npm -v
          pushd "$APP_PATH"
          npm ci
          npm run lint --if-present
          npm run test --if-present
          popd

      - name: Expo prebuild (iOS on macOS runner, in mobile/)
        script: |
          set -e
          pushd "$APP_PATH"
          npx expo prebuild --platform ios --non-interactive --clean
          popd
          # 必要に応じて $APP_PATH/ios 配下の Info.plist 等をここで書き換える

      - name: Install CocoaPods (mobile/ios)
        script: |
          set -e
          pushd "$APP_PATH/ios"
          pod repo update
          pod install
          popd

      - name: Apply signing profiles to Xcode project
        script: |
          set -e
          pushd "$APP_PATH/ios"
          xcode-project use-profiles
          popd

      - name: Detect workspace and scheme (under mobile/ios)
        script: |
          set -euo pipefail
          WORKSPACE=$(ls -1d "$APP_PATH"/ios/*.xcworkspace | head -n 1)
          if [ -z "${WORKSPACE:-}" ]; then
            echo "No .xcworkspace found under $APP_PATH/ios/"
            exit 1
          fi
          echo "XCODE_WORKSPACE=$WORKSPACE" >> $CM_ENV
          xcodebuild -list -json -workspace "$WORKSPACE" > xclist.json
          SCHEME=$(python3 -c 'import json,sys; d=json.load(open("xclist.json")); s=(d.get("workspace",{}).get("schemes") or d.get("project",{}).get("schemes") or []); print(s[0] if s else "")')
          if [ -z "$SCHEME" ]; then
            echo "No Xcode scheme detected"
            exit 1
          fi
          echo "Detected scheme: $SCHEME"
          echo "XCODE_SCHEME=$SCHEME" >> $CM_ENV

      - name: Verify signing settings
        script: |
          set -e
          xcodebuild -showBuildSettings \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" | egrep 'CODE_SIGN|PROVISION|DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER' || true

          echo "Installed provisioning profiles:"
          ls "$HOME/Library/MobileDevice/Provisioning Profiles" | wc -l || true

      # （必要なら有効化）ビルド番号の自動更新

      - name: Bump build number (CFBundleVersion)

        script: |

          set -e
          BUILD_NUMBER=$(date +%Y%m%d%H%M)
          echo "Setting CFBundleVersion to $BUILD_NUMBER"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$APP_PATH"/ios/*/Info.plist || true
          /usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$APP_PATH"/ios/*/Info.plist || true

      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

      - name: Upload to App Store Connect (no TestFlight submission)

        script: |

          set -e

          IPA_PATH="$(find "$CM_BUILD_DIR" -name '*.ipa' | head -n 1)"

          echo "Uploading IPA: $IPA_PATH"

          # Upload only to App Store Connect. This does NOT submit to TestFlight.
          app-store-connect publish --path "$IPA_PATH"
          # Next steps after upload:
          # - For external TestFlight submission, add --testflight and ensure Beta App Information
          #   (contact name, email, phone, feedback email) and a Beta Group are configured in App Store Connect.
          # - Alternatively submit from App Store Connect: TestFlight > select the build > Submit for Beta Review.
          # - For internal testing, add the uploaded build to an internal tester group in App Store Connect.

    artifacts:
      - $CM_BUILD_DIR/**/**/*.ipa
      - $CM_BUILD_DIR/**/xcodebuild.log
      - mobile/ios/build/**/*.dSYM
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/**/*.log

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
