workflows:
  ios-testflight:
    name: iOS TestFlight (Expo prebuild + Xcode + auto signing)
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: "Graspo2"

    environment:
      groups:
        - appstore

      vars:
        BUNDLE_ID: com.rietamura.graspo
        APP_PATH: mobile

    scripts:
      - name: Print versions and install JS deps (mobile/)
        script: |
          node -v
          npm -v
          pushd "$APP_PATH"
          npm ci
          npm run lint --if-present
          npm run test --if-present
          popd

      - name: Expo prebuild (iOS on macOS runner, in mobile/)
        script: |
          set -e
          pushd "$APP_PATH"
          npx expo prebuild --platform ios --non-interactive --clean
          popd

      - name: Install CocoaPods (mobile/ios)
        script: |
          set -e
          pushd "$APP_PATH/ios"
          pod repo update
          pod install
          popd

      - name: Initialize keychain and fetch/create signing files (automatic)
        script: |
          set -euo pipefail

          echo "Private key length: ${#APP_STORE_CONNECT_PRIVATE_KEY}"

          keychain initialize

          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

          keychain add-certificates

      - name: Apply signing profiles to Xcode project
        script: |
          set -e
          pushd "$APP_PATH/ios"
          xcode-project use-profiles
          popd

      - name: Detect workspace and scheme (under mobile/ios)
        script: |
          set -euo pipefail
          WORKSPACE=$(ls -1d "$APP_PATH"/ios/*.xcworkspace | head -n 1)
          SCHEME=$(xcodebuild -list -json -workspace "$WORKSPACE" | jq -r '.workspace.schemes[0]')
          echo "Detected workspace: $WORKSPACE"
          echo "Detected scheme: $SCHEME"
          echo "export WORKSPACE=$WORKSPACE" >> $CM_ENV_PATH
          echo "export SCHEME=$SCHEME" >> $CM_ENV_PATH

      - name: Build iOS app for release
        script: |
          set -euo pipefail
          pushd "$APP_PATH/ios"
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/Graspo.xcarchive" \
            archive CODE_SIGN_STYLE=Manual
          popd

      - name: Export IPA
        script: |
          set -euo pipefail
          xcode-project build-ipa --archive-path "$CM_BUILD_DIR/Graspo.xcarchive"

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/*.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
